version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Date and Time
          command: date -d 'today' "+%d-%m-%Y" 
      - run:
          bash ./test.sh
      - run:
          command: echo "This is for testing"
